name: Big Dumb Planet
favicon: null
layout_spectrum: 0.9751815018244088
typography_spectrum: 0.6410997589118779
title: Big Dumb Planet
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.27726521575823426
  lightness: 0.8096719987224787
  saturation: 0.5118485889397562
  rhythmicContrast: 0.617224512854591
purpose: []
